name: pipeline-ci-cd

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Melhoria 1: Cache de dependências para acelerar o build
      - name: Configurar Node.js e Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Instalar dependências (Clean Install)
        working-directory: ./backend
        run: npm ci # npm ci é mais rápido e seguro para CI que o npm install

      - name: Executar testes com Jest
        working-directory: ./backend
        run: npm test -- --coverage

  build-and-integration:
    needs: unit-test
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: adote_facil
      POSTGRES_HOST: adote-facil-postgres
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: 5432
      POSTGRES_CONTAINER_PORT: 6500
      # Adicionando a DATABASE_URL que o Prisma exige
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@adote-facil-postgres:5432/adote_facil

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Melhoria 2: Criação automatizada do .env para os containers
      - name: Criar arquivo .env
        run: |
          echo "POSTGRES_DB=${{ env.POSTGRES_DB }}" >> backend/.env
          echo "POSTGRES_HOST=${{ env.POSTGRES_HOST }}" >> backend/.env
          echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> backend/.env
          echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> backend/.env
          echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> backend/.env

      # Melhoria 3: Uso do --wait nativo (Substitui o sleep 10)
      - name: Subir containers e validar Saúde (Healthcheck)
        run: docker compose up -d --wait

      - name: Logs em caso de falha
        if: failure()
        run: docker compose logs

      - name: Encerrar containers
        run: docker compose down

  delivery:
    needs: build-and-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar artefato (ZIP)
        run: zip -r adote-facil-projeto.zip . -x '*.git*' '*.github*' '**/node_modules/*'

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: adote-facil-projeto
          path: adote-facil-projeto.zip
          retention-days: 5 # Define validade para não ocupar espaço infinito